# This file has been generated by node2nix 1.4.0. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-4_x"}:

let
  globalBuildInputs = pkgs.lib.attrValues (import ./supplement.nix {
    inherit nodeEnv;
    inherit (pkgs) fetchurl fetchgit;
  });
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
    inherit nodejs;
  };
  nodePackages = import ./node-packages.nix {
    inherit (pkgs) fetchurl fetchgit srcOnly;
    inherit nodeEnv globalBuildInputs;
  };
in
nodePackages // {
  # Disable npm install for electron-chromedriver because it would download
  # chromedriver
  electron-chromedriver = nodePackages.electron-chromedriver.override (oldAttrs: {
    dontNpmInstall = true;
  });
}
