# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, srcOnly, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "aes-js-2.1.1" = {
      name = "aes-js";
      packageName = "aes-js";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/aes-js/-/aes-js-2.1.1.tgz";
        sha1 = "68989763bbade2a39172ea48f4953d1272ff38a7";
      };
    };
    "bignumber.js-4.0.0" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-4.0.0.tgz";
        sha1 = "26b23a3240820fb6b875f07de822004c7d34b682";
      };
    };
    "bip39-2.3.0" = {
      name = "bip39";
      packageName = "bip39";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bip39/-/bip39-2.3.0.tgz";
        sha1 = "e4ee6c6d1bd90ca00ffd57ad446bdf8c017ff484";
      };
    };
    "blakejs-1.0.1" = {
      name = "blakejs";
      packageName = "blakejs";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/blakejs/-/blakejs-1.0.1.tgz";
        sha1 = "ae54b631fb4ab820c4f7a226a4b430a95f87065e";
      };
    };
    "classnames-2.2.5" = {
      name = "classnames";
      packageName = "classnames";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/classnames/-/classnames-2.2.5.tgz";
        sha1 = "fb3801d453467649ef3603c7d61a02bd129bde6d";
      };
    };
    "css-modules-require-hook-4.0.6" = {
      name = "css-modules-require-hook";
      packageName = "css-modules-require-hook";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-modules-require-hook/-/css-modules-require-hook-4.0.6.tgz";
        sha1 = "70a03b0ca3784e36e5a1dc1aa82ba068d53248bf";
      };
    };
    "electron-debug-1.1.0" = {
      name = "electron-debug";
      packageName = "electron-debug";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-debug/-/electron-debug-1.1.0.tgz";
        sha1 = "050a9c3f906fffc2492510cf8ac31d0f32a579e1";
      };
    };
    "electron-json-storage-3.0.4" = {
      name = "electron-json-storage";
      packageName = "electron-json-storage";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-json-storage/-/electron-json-storage-3.0.4.tgz";
        sha1 = "3b4e3e95e979eb1743edf55174f8daf69416c6fd";
      };
    };
    "electron-log-2.0.2" = {
      name = "electron-log";
      packageName = "electron-log";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-log/-/electron-log-2.0.2.tgz";
        sha1 = "ea7c3d584da1e02df48e68f16fb750b61e3ab05b";
      };
    };
    "es6-error-4.0.2" = {
      name = "es6-error";
      packageName = "es6-error";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-error/-/es6-error-4.0.2.tgz";
        sha1 = "eec5c726eacef51b7f6b73c20db6e1b13b069c98";
      };
    };
    "faker-3.1.0" = {
      name = "faker";
      packageName = "faker";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/faker/-/faker-3.1.0.tgz";
        sha1 = "0f908faf4e6ec02524e54a57e432c5c013e08c9f";
      };
    };
    "html-loader-0.4.5" = {
      name = "html-loader";
      packageName = "html-loader";
      version = "0.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-loader/-/html-loader-0.4.5.tgz";
        sha1 = "5fbcd87cd63a5c49a7fce2fe56f425e05729c68c";
      };
    };
    "immutability-helper-2.1.2" = {
      name = "immutability-helper";
      packageName = "immutability-helper";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutability-helper/-/immutability-helper-2.1.2.tgz";
        sha1 = "734506440d7209b74664dcadaa8ba14e73f2185b";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "markdown-loader-2.0.0" = {
      name = "markdown-loader";
      packageName = "markdown-loader";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-loader/-/markdown-loader-2.0.0.tgz";
        sha1 = "421862d38c4224fd3615eb648017ea385b562d78";
      };
    };
    "mobx-3.1.7" = {
      name = "mobx";
      packageName = "mobx";
      version = "3.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mobx/-/mobx-3.1.7.tgz";
        sha1 = "910c01f6e2f7e88ec47baabefee5fe667d37ac00";
      };
    };
    "mobx-react-4.1.5" = {
      name = "mobx-react";
      packageName = "mobx-react";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mobx-react/-/mobx-react-4.1.5.tgz";
        sha1 = "75cf4dbffc91b9cb23d56c060dfd8d2ca52450dc";
      };
    };
    "mobx-react-form-1.31.5" = {
      name = "mobx-react-form";
      packageName = "mobx-react-form";
      version = "1.31.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mobx-react-form/-/mobx-react-form-1.31.5.tgz";
        sha1 = "9216f81693eaab094326dbf36409dca5cbf360c0";
      };
    };
    "mobx-react-router-3.1.2" = {
      name = "mobx-react-router";
      packageName = "mobx-react-router";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mobx-react-router/-/mobx-react-router-3.1.2.tgz";
        sha1 = "83328b108393017148d86fea17f611de2d2aacdc";
      };
    };
    "moment-2.18.1" = {
      name = "moment";
      packageName = "moment";
      version = "2.18.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.18.1.tgz";
        sha1 = "c36193dd3ce1c2eed2adb7c802dbbc77a81b1c0f";
      };
    };
    "numeral-2.0.6" = {
      name = "numeral";
      packageName = "numeral";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/numeral/-/numeral-2.0.6.tgz";
        sha1 = "4ad080936d443c2561aed9f2197efffe25f4e506";
      };
    };
    "pdf.js-extract-0.0.5" = {
      name = "pdf.js-extract";
      packageName = "pdf.js-extract";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/pdf.js-extract/-/pdf.js-extract-0.0.5.tgz";
        sha1 = "d141942ee2e291e8fd851159ec15cf6930aa95ce";
      };
    };
    "postcss-5.2.16" = {
      name = "postcss";
      packageName = "postcss";
      version = "5.2.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-5.2.16.tgz";
        sha1 = "732b3100000f9ff8379a48a53839ed097376ad57";
      };
    };
    "qrcode.react-0.6.1" = {
      name = "qrcode.react";
      packageName = "qrcode.react";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qrcode.react/-/qrcode.react-0.6.1.tgz";
        sha1 = "e718192d17cdf87cb1f156a34cea16dd67575932";
      };
    };
    "random-words-0.0.1" = {
      name = "random-words";
      packageName = "random-words";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/random-words/-/random-words-0.0.1.tgz";
        sha1 = "40e30092033ad8fb60d66ad15be3620d3c25c41f";
      };
    };
    "raw-loader-0.5.1" = {
      name = "raw-loader";
      packageName = "raw-loader";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-loader/-/raw-loader-0.5.1.tgz";
        sha1 = "0c3d0beaed8a01c966d9787bf778281252a979aa";
      };
    };
    "react-15.4.2" = {
      name = "react";
      packageName = "react";
      version = "15.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-15.4.2.tgz";
        sha1 = "41f7991b26185392ba9bae96c8889e7e018397ef";
      };
    };
    "react-addons-css-transition-group-15.4.2" = {
      name = "react-addons-css-transition-group";
      packageName = "react-addons-css-transition-group";
      version = "15.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-addons-css-transition-group/-/react-addons-css-transition-group-15.4.2.tgz";
        sha1 = "b7828834dfa14229fe07750e331e8a8cb6fb7745";
      };
    };
    "react-copy-to-clipboard-4.2.3" = {
      name = "react-copy-to-clipboard";
      packageName = "react-copy-to-clipboard";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-copy-to-clipboard/-/react-copy-to-clipboard-4.2.3.tgz";
        sha1 = "268c5a0fbde9a95d96145014e7f85110b0e7fb8e";
      };
    };
    "react-css-themr-2.0.0" = {
      name = "react-css-themr";
      packageName = "react-css-themr";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-css-themr/-/react-css-themr-2.0.0.tgz";
        sha1 = "c4f93b9284009d9b4565121f09eb6b2bf402c3ef";
      };
    };
    "react-dom-15.4.2" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "15.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-15.4.2.tgz";
        sha1 = "015363f05b0a1fd52ae9efdd3a0060d90695208f";
      };
    };
    "react-dropzone-3.12.2" = {
      name = "react-dropzone";
      packageName = "react-dropzone";
      version = "3.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dropzone/-/react-dropzone-3.12.2.tgz";
        sha1 = "7e66a37322a80cf26a205d749ecf8cad0d90aa6f";
      };
    };
    "react-intl-2.2.3" = {
      name = "react-intl";
      packageName = "react-intl";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-intl/-/react-intl-2.2.3.tgz";
        sha1 = "8eebb03cddc38b337ed22fab78037ab53a594270";
      };
    };
    "react-markdown-2.5.0" = {
      name = "react-markdown";
      packageName = "react-markdown";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-markdown/-/react-markdown-2.5.0.tgz";
        sha1 = "b1c61904fee5895886803bd9df7db23c3dc3a89e";
      };
    };
    "react-number-format-1.1.2" = {
      name = "react-number-format";
      packageName = "react-number-format";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-number-format/-/react-number-format-1.1.2.tgz";
        sha1 = "74d8478fa5cdeed55637f392597a0911157e2568";
      };
    };
    "react-polymorph-0.3.1" = {
      name = "react-polymorph";
      packageName = "react-polymorph";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-polymorph/-/react-polymorph-0.3.1.tgz";
        sha1 = "639c6cf607b6237c1025d1a65efab61a5358a1af";
      };
    };
    "react-router-3.0.3" = {
      name = "react-router";
      packageName = "react-router";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-router/-/react-router-3.0.3.tgz";
        sha1 = "e95304b2e418482e5ecff2699d2b8aae52d5f884";
      };
    };
    "react-svg-inline-2.0.0" = {
      name = "react-svg-inline";
      packageName = "react-svg-inline";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-svg-inline/-/react-svg-inline-2.0.0.tgz";
        sha1 = "0a4f60895588eecc7616af3a511d087801163600";
      };
    };
    "recharts-1.0.0-alpha.4" = {
      name = "recharts";
      packageName = "recharts";
      version = "1.0.0-alpha.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/recharts/-/recharts-1.0.0-alpha.4.tgz";
        sha1 = "74b05457696987755bc05e8d6232ab5c58648676";
      };
    };
    "route-parser-0.0.5" = {
      name = "route-parser";
      packageName = "route-parser";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/route-parser/-/route-parser-0.0.5.tgz";
        sha1 = "7d1d09d335e49094031ea16991a4a79b01bbe1f4";
      };
    };
    "source-map-support-0.4.14" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.14.tgz";
        sha1 = "9d4463772598b86271b4f523f6c1f4e02a7d6aef";
      };
    };
    "validator-6.3.0" = {
      name = "validator";
      packageName = "validator";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-6.3.0.tgz";
        sha1 = "47ce23ed8d4eaddfa9d4b8ef0071b6cf1078d7c8";
      };
    };
    "wallet-address-validator-0.1.0" = {
      name = "wallet-address-validator";
      packageName = "wallet-address-validator";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wallet-address-validator/-/wallet-address-validator-0.1.0.tgz";
        sha1 = "f9cf29c72fce947571e1c418c7f91e57c52bc485";
      };
    };
    "winston-2.3.1" = {
      name = "winston";
      packageName = "winston";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.3.1.tgz";
        sha1 = "0b48420d978c01804cf0230b648861598225a119";
      };
    };
    "winston-papertrail-1.0.4" = {
      name = "winston-papertrail";
      packageName = "winston-papertrail";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston-papertrail/-/winston-papertrail-1.0.4.tgz";
        sha1 = "95b40e2f518cf12975207b272caab08c8ea448f9";
      };
    };
    "ws-3.1.0" = {
      name = "ws";
      packageName = "ws";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-3.1.0.tgz";
        sha512 = "07wdh2llaz8j5nbjpvl1zbbksw2pikqnw243c6a1ifmshp095hgam79vv5nbp1pjwnlm120m4d3sih9iwm5mkc46im03jb5l6l3ykjd";
      };
    };
    "create-hash-1.1.3" = {
      name = "create-hash";
      packageName = "create-hash";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hash/-/create-hash-1.1.3.tgz";
        sha1 = "606042ac8b9262750f483caddab0f5819172d8fd";
      };
    };
    "pbkdf2-3.0.14" = {
      name = "pbkdf2";
      packageName = "pbkdf2";
      version = "3.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/pbkdf2/-/pbkdf2-3.0.14.tgz";
        sha512 = "30bb7vx0m1k1m3d1i1khgvmgddx3ahqgprs421ssrh5plpx50k5bazsj67gdi7qiknircqy59yxbclq95s2rnmk8ysgkqdpsddijfw2";
      };
    };
    "randombytes-2.0.5" = {
      name = "randombytes";
      packageName = "randombytes";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/randombytes/-/randombytes-2.0.5.tgz";
        sha512 = "293m4ffiafbjg0b99a2k78wiffmlwc2v7cigrn5l3n7555x7qxyr34sp0s4p713vwlaf0ny5n57iysgkz08slld3hzw8ci1a2gxjgpi";
      };
    };
    "unorm-1.4.1" = {
      name = "unorm";
      packageName = "unorm";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unorm/-/unorm-1.4.1.tgz";
        sha1 = "364200d5f13646ca8bcd44490271335614792300";
      };
    };
    "cipher-base-1.0.4" = {
      name = "cipher-base";
      packageName = "cipher-base";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cipher-base/-/cipher-base-1.0.4.tgz";
        sha512 = "3cm9kdc1sv7pakzlhrc1pazdvg9lk4hv31lximwbcrgmwfzg6imxrndszgx9yzlizknfh2b73cr7b5mfcv50bldpyq6jr5s4zknsj1a";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ripemd160-2.0.1" = {
      name = "ripemd160";
      packageName = "ripemd160";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ripemd160/-/ripemd160-2.0.1.tgz";
        sha1 = "0f4584295c53a3628af7e6d79aca21ce57d1c6e7";
      };
    };
    "sha.js-2.4.9" = {
      name = "sha.js";
      packageName = "sha.js";
      version = "2.4.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha.js/-/sha.js-2.4.9.tgz";
        sha512 = "3l96mlw71zgkmfm9madd3jcndrpm2fm4jz2q5gz9mbm27mdg89hsbrg22pfl32ha76xa3pza83m2mc3b47pnq19mz3j6vkasn9dxk0v";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "1p28rllll1w65yzq5azi4izx962399xdsdlfbaynn7vmp981hiss05jhiy9hm7sbbfk3b4dhlcv0zy07fc59mnc07hdv6wcgqkcvawh";
      };
    };
    "hash-base-2.0.2" = {
      name = "hash-base";
      packageName = "hash-base";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hash-base/-/hash-base-2.0.2.tgz";
        sha1 = "66ea1d856db4e8a5470cadf6fce23ae5244ef2e1";
      };
    };
    "create-hmac-1.1.6" = {
      name = "create-hmac";
      packageName = "create-hmac";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-hmac/-/create-hmac-1.1.6.tgz";
        sha1 = "acb9e221a4e17bdb076e90657c42b93e3726cf06";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "0q0fsr8bk1m83z0am0h2xn09vyfcf18adscxms8hclznwks1aihsisd96h8npx0idq5wwnypnqrkyk25m5d9zh3dk7rjs29nybc8bkc";
      };
    };
    "generic-names-1.0.3" = {
      name = "generic-names";
      packageName = "generic-names";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/generic-names/-/generic-names-1.0.3.tgz";
        sha1 = "2d786a121aee508876796939e8e3bff836c20917";
      };
    };
    "glob-to-regexp-0.1.0" = {
      name = "glob-to-regexp";
      packageName = "glob-to-regexp";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-to-regexp/-/glob-to-regexp-0.1.0.tgz";
        sha1 = "e0369d426578fd456d47dc23b09de05c1da9ea5d";
      };
    };
    "icss-replace-symbols-1.1.0" = {
      name = "icss-replace-symbols";
      packageName = "icss-replace-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/icss-replace-symbols/-/icss-replace-symbols-1.1.0.tgz";
        sha1 = "06ea6f83679a7749e386cfe1fe812ae5db223ded";
      };
    };
    "postcss-modules-extract-imports-1.2.0" = {
      name = "postcss-modules-extract-imports";
      packageName = "postcss-modules-extract-imports";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-extract-imports/-/postcss-modules-extract-imports-1.2.0.tgz";
        sha1 = "66140ecece38ef06bf0d3e355d69bf59d141ea85";
      };
    };
    "postcss-modules-local-by-default-1.2.0" = {
      name = "postcss-modules-local-by-default";
      packageName = "postcss-modules-local-by-default";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-local-by-default/-/postcss-modules-local-by-default-1.2.0.tgz";
        sha1 = "f7d80c398c5a393fa7964466bd19500a7d61c069";
      };
    };
    "postcss-modules-parser-1.1.1" = {
      name = "postcss-modules-parser";
      packageName = "postcss-modules-parser";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-parser/-/postcss-modules-parser-1.1.1.tgz";
        sha1 = "95f71ad7916f0f39207bb81c401336c8d245738c";
      };
    };
    "postcss-modules-scope-1.1.0" = {
      name = "postcss-modules-scope";
      packageName = "postcss-modules-scope";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-scope/-/postcss-modules-scope-1.1.0.tgz";
        sha1 = "d6ea64994c79f97b62a72b426fbe6056a194bb90";
      };
    };
    "postcss-modules-values-1.3.0" = {
      name = "postcss-modules-values";
      packageName = "postcss-modules-values";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-values/-/postcss-modules-values-1.3.0.tgz";
        sha1 = "ecffa9d7e192518389f42ad0e83f72aec456ea20";
      };
    };
    "seekout-1.0.2" = {
      name = "seekout";
      packageName = "seekout";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/seekout/-/seekout-1.0.2.tgz";
        sha1 = "09ba9f1bd5b46fbb134718eb19a68382cbb1b9c9";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "loader-utils-0.2.17" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "0.2.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-0.2.17.tgz";
        sha1 = "f86e6374d43205a6e6c60e9196f17c0299bfb348";
      };
    };
    "big.js-3.2.0" = {
      name = "big.js";
      packageName = "big.js";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/big.js/-/big.js-3.2.0.tgz";
        sha512 = "3qicqys1bg16slzbzjn3f0fir82r4d1h6lvy5y0cqqwzbs2iaxf93xgi6x47m7l87i102ifjn4qvjbf764gyncsxcqw7lw33mk7y4zs";
      };
    };
    "emojis-list-2.1.0" = {
      name = "emojis-list";
      packageName = "emojis-list";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emojis-list/-/emojis-list-2.1.0.tgz";
        sha1 = "4daa4d9db00f9819880c79fa457ae5b09a1fd389";
      };
    };
    "json5-0.5.1" = {
      name = "json5";
      packageName = "json5";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-0.5.1.tgz";
        sha1 = "1eade7acc012034ad84e2396767ead9fa5495821";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "postcss-6.0.14" = {
      name = "postcss";
      packageName = "postcss";
      version = "6.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-6.0.14.tgz";
        sha512 = "2id33g6232s35n25daqrkz0bvzm2zmhlkfzmigkgia5q4jy9xg38spppmsdg0qswjankyi28wrbjsdwhczqfkx7h71gg8dmzz8p779l";
      };
    };
    "chalk-2.3.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.3.0.tgz";
        sha512 = "3fj8njcdcvyplivm2fj19lqw8qv7gb8v7gd6a223pmn8f3di4zwkhyb09vzlmw3pnk4ib88kp4cg8r9i5k5rskalzdfh1l23ljp6gh3";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "3p7hw8p69ikj5mwapmqkacsjnbvdfk5ylyamjg9x5izkl717xvzj0vk3fnmx1n4pf54h5rs7r8ig5kk4jv4ycqqj0hv75cnx6k1lf2j";
      };
    };
    "supports-color-4.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-4.5.0.tgz";
        sha1 = "be7a0de484dec5c5cddf8b3d59125044912f635b";
      };
    };
    "ansi-styles-3.2.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.0.tgz";
        sha512 = "2x19fs1qvg7ifsdvii4g8kqpa5hir1lm0k0y0fz6dhm5c8gh4z9il4wqczl078p2ikmrav23dmj86cxy8y1j22k4mv59d8qq6c8wx1n";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "color-convert-1.9.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.1.tgz";
        sha512 = "32rj1090g95xcvm0d2ya6jbqdhiy9w2wv3picdy33fzrm455v0gi7g4n8lw0n31g37wwbdnz7lxjsisgbsaqz1d10j9nh5hi2f9lccs";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "has-flag-2.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-2.0.0.tgz";
        sha1 = "e8207af1cc7b30d446cc70b734b5e8be18f88d51";
      };
    };
    "css-selector-tokenizer-0.7.0" = {
      name = "css-selector-tokenizer";
      packageName = "css-selector-tokenizer";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-selector-tokenizer/-/css-selector-tokenizer-0.7.0.tgz";
        sha1 = "e6988474ae8c953477bf5e7efecfceccd9cf4c86";
      };
    };
    "cssesc-0.1.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-0.1.0.tgz";
        sha1 = "c814903e45623371a0477b40109aaafbeeaddbb4";
      };
    };
    "fastparse-1.1.1" = {
      name = "fastparse";
      packageName = "fastparse";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastparse/-/fastparse-1.1.1.tgz";
        sha1 = "d1e2643b38a94d7583b479060e6c4affc94071f8";
      };
    };
    "regexpu-core-1.0.0" = {
      name = "regexpu-core";
      packageName = "regexpu-core";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexpu-core/-/regexpu-core-1.0.0.tgz";
        sha1 = "86a763f58ee4d7c2f6b102e4764050de7ed90c6b";
      };
    };
    "regenerate-1.3.3" = {
      name = "regenerate";
      packageName = "regenerate";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerate/-/regenerate-1.3.3.tgz";
        sha512 = "2rbbgk0fggg02f798h8whyk1d5ky4pqmbjdaia7hzfpmxd16dy4nmd0wd6qr1xgic5434h305cmhp75f4sd4zyvww531b4xcva6hnld";
      };
    };
    "regjsgen-0.2.0" = {
      name = "regjsgen";
      packageName = "regjsgen";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regjsgen/-/regjsgen-0.2.0.tgz";
        sha1 = "6c016adeac554f75823fe37ac05b92d5a4edb1f7";
      };
    };
    "regjsparser-0.1.5" = {
      name = "regjsparser";
      packageName = "regjsparser";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/regjsparser/-/regjsparser-0.1.5.tgz";
        sha1 = "7ee8f84dc6fa792d3fd0ae228d24bd949ead205c";
      };
    };
    "jsesc-0.5.0" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-0.5.0.tgz";
        sha1 = "e7dee66e35d6fc16f710fe91d5cf69f70f08911d";
      };
    };
    "lodash.foreach-3.0.3" = {
      name = "lodash.foreach";
      packageName = "lodash.foreach";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.foreach/-/lodash.foreach-3.0.3.tgz";
        sha1 = "6fd7efb79691aecd67fdeac2761c98e701d6c39a";
      };
    };
    "lodash._arrayeach-3.0.0" = {
      name = "lodash._arrayeach";
      packageName = "lodash._arrayeach";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._arrayeach/-/lodash._arrayeach-3.0.0.tgz";
        sha1 = "bab156b2a90d3f1bbd5c653403349e5e5933ef9e";
      };
    };
    "lodash._baseeach-3.0.4" = {
      name = "lodash._baseeach";
      packageName = "lodash._baseeach";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._baseeach/-/lodash._baseeach-3.0.4.tgz";
        sha1 = "cf8706572ca144e8d9d75227c990da982f932af3";
      };
    };
    "lodash._bindcallback-3.0.1" = {
      name = "lodash._bindcallback";
      packageName = "lodash._bindcallback";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._bindcallback/-/lodash._bindcallback-3.0.1.tgz";
        sha1 = "e531c27644cf8b57a99e17ed95b35c748789392e";
      };
    };
    "lodash.isarray-3.0.4" = {
      name = "lodash.isarray";
      packageName = "lodash.isarray";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isarray/-/lodash.isarray-3.0.4.tgz";
        sha1 = "79e4eb88c36a8122af86f844aa9bcd851b5fbb55";
      };
    };
    "lodash.keys-3.1.2" = {
      name = "lodash.keys";
      packageName = "lodash.keys";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.keys/-/lodash.keys-3.1.2.tgz";
        sha1 = "4dbc0472b156be50a0b286855d1bd0b0c656098a";
      };
    };
    "lodash._getnative-3.9.1" = {
      name = "lodash._getnative";
      packageName = "lodash._getnative";
      version = "3.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._getnative/-/lodash._getnative-3.9.1.tgz";
        sha1 = "570bc7dede46d61cdcde687d65d3eecbaa3aaff5";
      };
    };
    "lodash.isarguments-3.1.0" = {
      name = "lodash.isarguments";
      packageName = "lodash.isarguments";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isarguments/-/lodash.isarguments-3.1.0.tgz";
        sha1 = "2f573d85c6a24289ff00663b491c1d338ff3458a";
      };
    };
    "electron-is-dev-0.1.2" = {
      name = "electron-is-dev";
      packageName = "electron-is-dev";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-is-dev/-/electron-is-dev-0.1.2.tgz";
        sha1 = "8a1043e32b3a1da1c3f553dce28ce764246167e3";
      };
    };
    "electron-localshortcut-0.6.1" = {
      name = "electron-localshortcut";
      packageName = "electron-localshortcut";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-localshortcut/-/electron-localshortcut-0.6.1.tgz";
        sha1 = "c4e268c38a6e42f40de5618fc906d1ed608f11aa";
      };
    };
    "async-2.6.0" = {
      name = "async";
      packageName = "async";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.0.tgz";
        sha512 = "0zp4b5788400npi1ixjry5x3a4m21c8pnknk8v731rgnwnjbp5ijmfcf5ppmn1ap4a04md1s9dr8n9ygdvrmiai590v0k6dby1wc1y4";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "rimraf-2.6.2" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.2.tgz";
        sha512 = "3kmrqh8xli7rzfm8wc6j9lp0c6vml172iv3z088an9xlwl1xvkvh3fn92za66ms4c9yww80qa5kan31k1z1ypqvkchmh1mznb09xdwn";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha512 = "08vjxzixc9dwc1hn5pd60yyij98krk2pr758aiga97r02ncvaqx1hidi95wk470k1v84gg4alls9bm52m77174z128bgf13b61x951h";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.8" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz";
        sha1 = "c07b211c7c952ec1f8efd51a77ef0d1d3990a292";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "es6-templates-0.2.3" = {
      name = "es6-templates";
      packageName = "es6-templates";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-templates/-/es6-templates-0.2.3.tgz";
        sha1 = "5cb9ac9fb1ded6eb1239342b81d792bbb4078ee4";
      };
    };
    "html-minifier-3.5.8" = {
      name = "html-minifier";
      packageName = "html-minifier";
      version = "3.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/html-minifier/-/html-minifier-3.5.8.tgz";
        sha512 = "29sg4r25g8awvmlyzjip0c216bjcd0nq730jd5vihagf3vpxw070gi5nd7z7333givgislxfylv4jrxn4ngqxgnwns5lg3xy3lc6zjr";
      };
    };
    "loader-utils-1.1.0" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-1.1.0.tgz";
        sha1 = "c98aef488bcceda2ffb5e2de646d6a754429f5cd";
      };
    };
    "recast-0.11.23" = {
      name = "recast";
      packageName = "recast";
      version = "0.11.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/recast/-/recast-0.11.23.tgz";
        sha1 = "451fd3004ab1e4df9b4e4b66376b2a21912462d3";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "ast-types-0.9.6" = {
      name = "ast-types";
      packageName = "ast-types";
      version = "0.9.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ast-types/-/ast-types-0.9.6.tgz";
        sha1 = "102c9e9e9005d3e7e3829bf0c4fa24ee862ee9b9";
      };
    };
    "esprima-3.1.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.1.3.tgz";
        sha1 = "fdca51cee6133895e3c88d535ce49dbff62a4633";
      };
    };
    "private-0.1.8" = {
      name = "private";
      packageName = "private";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/private/-/private-0.1.8.tgz";
        sha512 = "2dgznnpxsgy9bgp4kfby1is72blvca4lhmqb3nlja8yiig1v52c12p5yw0aag8jqazhkqvihpxmqf9gsjlg5dr1jb56jxzgnqrazy2n";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "camel-case-3.0.0" = {
      name = "camel-case";
      packageName = "camel-case";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camel-case/-/camel-case-3.0.0.tgz";
        sha1 = "ca3c3688a4e9cf3a4cda777dc4dcbc713249cf73";
      };
    };
    "clean-css-4.1.9" = {
      name = "clean-css";
      packageName = "clean-css";
      version = "4.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/clean-css/-/clean-css-4.1.9.tgz";
        sha1 = "35cee8ae7687a49b98034f70de00c4edd3826301";
      };
    };
    "commander-2.12.2" = {
      name = "commander";
      packageName = "commander";
      version = "2.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.12.2.tgz";
        sha512 = "007wb3baahjcrv17kgxryqjlsyr3c3kl2y07p85m4ia78pba9xyjr3cgi95jjrwq8qq550s78hj06f7z0ab8ssrxk6w06afjsmxln84";
      };
    };
    "he-1.1.1" = {
      name = "he";
      packageName = "he";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.1.1.tgz";
        sha1 = "93410fd21b009735151f8868c2f271f3427e23fd";
      };
    };
    "ncname-1.0.0" = {
      name = "ncname";
      packageName = "ncname";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncname/-/ncname-1.0.0.tgz";
        sha1 = "5b57ad18b1ca092864ef62b0b1ed8194f383b71c";
      };
    };
    "param-case-2.1.1" = {
      name = "param-case";
      packageName = "param-case";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/param-case/-/param-case-2.1.1.tgz";
        sha1 = "df94fd8cf6531ecf75e6bef9a0858fbc72be2247";
      };
    };
    "relateurl-0.2.7" = {
      name = "relateurl";
      packageName = "relateurl";
      version = "0.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/relateurl/-/relateurl-0.2.7.tgz";
        sha1 = "54dbf377e51440aca90a4cd274600d3ff2d888a9";
      };
    };
    "uglify-js-3.3.3" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.3.3.tgz";
        sha512 = "3zcfjaa93ah92gh02p5vx13fyw3cqdhadj424mmcfd4jlpb3dwlmhf014fy5a1gnzwvwdcilg8p4y7b7hlxh3vys0rwp941vrlz4nbf";
      };
    };
    "no-case-2.3.2" = {
      name = "no-case";
      packageName = "no-case";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-case/-/no-case-2.3.2.tgz";
        sha512 = "34msnfifpdmxl414b8rch1p1six59jd9251b7wkb37n78fa84xfa5f5f5cxxp477wb846nfrsg6b1py3rahz4xdpk17lzzy9kvdjr5f";
      };
    };
    "upper-case-1.1.3" = {
      name = "upper-case";
      packageName = "upper-case";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/upper-case/-/upper-case-1.1.3.tgz";
        sha1 = "f6b4501c2ec4cdd26ba78be7222961de77621598";
      };
    };
    "lower-case-1.1.4" = {
      name = "lower-case";
      packageName = "lower-case";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lower-case/-/lower-case-1.1.4.tgz";
        sha1 = "9a2cabd1b9e8e0ae993a4bf7d5875c39c42e8eac";
      };
    };
    "xml-char-classes-1.0.0" = {
      name = "xml-char-classes";
      packageName = "xml-char-classes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml-char-classes/-/xml-char-classes-1.0.0.tgz";
        sha1 = "64657848a20ffc5df583a42ad8a277b4512bbc4d";
      };
    };
    "invariant-2.2.2" = {
      name = "invariant";
      packageName = "invariant";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/invariant/-/invariant-2.2.2.tgz";
        sha1 = "9e1f56ac0acdb6bf303306f338be3b204ae60360";
      };
    };
    "loose-envify-1.3.1" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.3.1.tgz";
        sha1 = "d1a8ad33fa9ce0e713d65fdd0ac8b748d478c848";
      };
    };
    "js-tokens-3.0.2" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz";
        sha1 = "9866df395102130e38f7f996bceb65443209c25b";
      };
    };
    "marked-0.3.9" = {
      name = "marked";
      packageName = "marked";
      version = "0.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-0.3.9.tgz";
        sha512 = "0pwzm37c83y03v5kd0py5nd7bfzm8h07ibq73j6kx2sjyj62p9c3swp9nk64nb4w67gdq4i5xp05673k3vsxwvwj3gi2pv9vk8nwvlx";
      };
    };
    "hoist-non-react-statics-1.2.0" = {
      name = "hoist-non-react-statics";
      packageName = "hoist-non-react-statics";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoist-non-react-statics/-/hoist-non-react-statics-1.2.0.tgz";
        sha1 = "aa448cf0986d55cc40773b17174b7dd066cb7cfb";
      };
    };
    "pdfjs-dist-for-node-1.0.893" = {
      name = "pdfjs-dist-for-node";
      packageName = "pdfjs-dist-for-node";
      version = "1.0.893";
      src = fetchurl {
        url = "https://registry.npmjs.org/pdfjs-dist-for-node/-/pdfjs-dist-for-node-1.0.893.tgz";
        sha1 = "10be171dc212f4aa862528b43258d745399bc3ad";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "js-base64-2.4.0" = {
      name = "js-base64";
      packageName = "js-base64";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-base64/-/js-base64-2.4.0.tgz";
        sha512 = "0l77939c8i8iwd2rmypxipqrfgkg8m2xh7qkg41ka8h2mx62wx2lhy4v51ch43gr2ap6q7mqmbj6djfppwp9cmz35px3xnzngxmvs2r";
      };
    };
    "supports-color-3.2.3" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "3.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-3.2.3.tgz";
        sha1 = "65ac0504b3954171d8a64946b2ae3cbb8a5f54f6";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "has-flag-1.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-1.0.0.tgz";
        sha1 = "9d9e793165ce017a00f00418c43f942a7b1d11fa";
      };
    };
    "qr.js-0.0.0" = {
      name = "qr.js";
      packageName = "qr.js";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qr.js/-/qr.js-0.0.0.tgz";
        sha1 = "cace86386f59a0db8050fa90d9b6b0e88a1e364f";
      };
    };
    "fbjs-0.8.16" = {
      name = "fbjs";
      packageName = "fbjs";
      version = "0.8.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/fbjs/-/fbjs-0.8.16.tgz";
        sha1 = "5e67432f550dc41b572bf55847b8aca64e5337db";
      };
    };
    "core-js-1.2.7" = {
      name = "core-js";
      packageName = "core-js";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-1.2.7.tgz";
        sha1 = "652294c14651db28fa93bd2d5ff2983a4f08c636";
      };
    };
    "isomorphic-fetch-2.2.1" = {
      name = "isomorphic-fetch";
      packageName = "isomorphic-fetch";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-fetch/-/isomorphic-fetch-2.2.1.tgz";
        sha1 = "611ae1acf14f5e81f729507472819fe9733558a9";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha512 = "17cn4nns2nxh9r0pdiqsqx3fpvaa82c1mhcr8r84k2a9hkpb0mj4bxzfbg3l9iy74yn9hj6mh2gsddsi3v939a1zp7ycbzqkxfm12cy";
      };
    };
    "setimmediate-1.0.5" = {
      name = "setimmediate";
      packageName = "setimmediate";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz";
        sha1 = "290cbb232e306942d7d7ea9b83732ab7856f8285";
      };
    };
    "ua-parser-js-0.7.17" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.17.tgz";
        sha512 = "39ac4xrr9v9ya7rbn5cz8dss5j3s36yhpj9qrhfxxqzgy1vljns0qfyv7d76lqgdgdbfbrd91kb5x7jlg0fw2r4f3kml0v8xmv545xr";
      };
    };
    "node-fetch-1.7.3" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-1.7.3.tgz";
        sha512 = "0lz5m15w7qaks0a0s3dm0crsjrsd123dy00pn6qwcp50zfjykxkp22i5ymh6smlc0ags38nmdxlxw9yyq509azlv8kcdvdiq857h5in";
      };
    };
    "whatwg-fetch-2.0.3" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-2.0.3.tgz";
        sha1 = "9c84ec2dcf68187ff00bc64e1274b442176e1c84";
      };
    };
    "encoding-0.1.12" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.12.tgz";
        sha1 = "538b66f3ee62cd1ab51ec323829d1f9480c74beb";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "iconv-lite-0.4.19" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.19.tgz";
        sha512 = "0jj1pdq3j9ak8cixn2kjp7ip8hf3xgnb85j4jr32yf9rry620v9072c0kk577mllfk1zl9wzs5ypwzbp7vbhf7j31d5rrqgwb0nldm1";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "copy-to-clipboard-3.0.8" = {
      name = "copy-to-clipboard";
      packageName = "copy-to-clipboard";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-to-clipboard/-/copy-to-clipboard-3.0.8.tgz";
        sha512 = "0mk5963cra6d0rnifr7x06chgpslbpzvdrq87b4kydshs7bzw0wf65vryp3wcrjf6hfjiarqgzhlxkwa10x8nrmgg323i1aixwrswbk";
      };
    };
    "toggle-selection-1.0.6" = {
      name = "toggle-selection";
      packageName = "toggle-selection";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/toggle-selection/-/toggle-selection-1.0.6.tgz";
        sha1 = "6e45b1263f2017fa0acc7d89d78b15b8bf77da32";
      };
    };
    "attr-accept-1.1.0" = {
      name = "attr-accept";
      packageName = "attr-accept";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/attr-accept/-/attr-accept-1.1.0.tgz";
        sha1 = "b5cd35227f163935a8f1de10ed3eba16941f6be6";
      };
    };
    "intl-format-cache-2.1.0" = {
      name = "intl-format-cache";
      packageName = "intl-format-cache";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/intl-format-cache/-/intl-format-cache-2.1.0.tgz";
        sha1 = "04a369fecbfad6da6005bae1f14333332dcf9316";
      };
    };
    "intl-messageformat-1.3.0" = {
      name = "intl-messageformat";
      packageName = "intl-messageformat";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/intl-messageformat/-/intl-messageformat-1.3.0.tgz";
        sha1 = "f7d926aded7a3ab19b2dc601efd54e99a4bd4eae";
      };
    };
    "intl-relativeformat-1.3.0" = {
      name = "intl-relativeformat";
      packageName = "intl-relativeformat";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/intl-relativeformat/-/intl-relativeformat-1.3.0.tgz";
        sha1 = "893dc7076fccd380cf091a2300c380fa57ace45b";
      };
    };
    "intl-messageformat-parser-1.2.0" = {
      name = "intl-messageformat-parser";
      packageName = "intl-messageformat-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/intl-messageformat-parser/-/intl-messageformat-parser-1.2.0.tgz";
        sha1 = "5906b7f953ab7470e0dc8549097b648b991892ff";
      };
    };
    "commonmark-0.24.0" = {
      name = "commonmark";
      packageName = "commonmark";
      version = "0.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commonmark/-/commonmark-0.24.0.tgz";
        sha1 = "b80de0182c546355643aa15db12bfb282368278f";
      };
    };
    "commonmark-react-renderer-4.3.4" = {
      name = "commonmark-react-renderer";
      packageName = "commonmark-react-renderer";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/commonmark-react-renderer/-/commonmark-react-renderer-4.3.4.tgz";
        sha512 = "1m7yawbg69dapbyhqpwjl1cz975nviqggx3y6i9mnw2qm7w1r309qgm0j7c28dbydf9ivqn47wgf4d8492pd5dny18v7pq8gfip7x7v";
      };
    };
    "in-publish-2.0.0" = {
      name = "in-publish";
      packageName = "in-publish";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/in-publish/-/in-publish-2.0.0.tgz";
        sha1 = "e20ff5e3a2afc2690320b6dc552682a9c7fadf51";
      };
    };
    "prop-types-15.6.0" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.6.0.tgz";
        sha1 = "ceaf083022fc46b4a35f69e13ef75aed0d639856";
      };
    };
    "entities-1.1.1" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.1.tgz";
        sha1 = "6e5c2d0a5621b5dadaecef80b90edfb5cd7772f0";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "string.prototype.repeat-0.2.0" = {
      name = "string.prototype.repeat";
      packageName = "string.prototype.repeat";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.repeat/-/string.prototype.repeat-0.2.0.tgz";
        sha1 = "aba36de08dcee6a5a337d49b2ea1da1b28fc0ecf";
      };
    };
    "lodash.assign-4.2.0" = {
      name = "lodash.assign";
      packageName = "lodash.assign";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.assign/-/lodash.assign-4.2.0.tgz";
        sha1 = "0d99f3ccd7a6d261d19bdaeb9245005d285808e7";
      };
    };
    "lodash.isplainobject-4.0.6" = {
      name = "lodash.isplainobject";
      packageName = "lodash.isplainobject";
      version = "4.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.isplainobject/-/lodash.isplainobject-4.0.6.tgz";
        sha1 = "7c526a52d89b45c45cc690b88163be0497f550cb";
      };
    };
    "pascalcase-0.1.1" = {
      name = "pascalcase";
      packageName = "pascalcase";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascalcase/-/pascalcase-0.1.1.tgz";
        sha1 = "b363e55e8006ca6fe21784d2db22bd15d7917f14";
      };
    };
    "xss-filters-1.2.7" = {
      name = "xss-filters";
      packageName = "xss-filters";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/xss-filters/-/xss-filters-1.2.7.tgz";
        sha1 = "59fa1de201f36f2f3470dcac5f58ccc2830b0a9a";
      };
    };
    "postinstall-build-5.0.1" = {
      name = "postinstall-build";
      packageName = "postinstall-build";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postinstall-build/-/postinstall-build-5.0.1.tgz";
        sha1 = "b917a9079b26178d9a24af5a5cd8cb4a991d11b9";
      };
    };
    "react-modal-2.4.1" = {
      name = "react-modal";
      packageName = "react-modal";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-modal/-/react-modal-2.4.1.tgz";
        sha512 = "1d252dzd81sg394pdl34ib2gpqna8g7gix2bzjf90p053gav7bbpc435d18khad26r805vm1cv4rb3swiwknm0lpwab34bagjgh4r6x";
      };
    };
    "exenv-1.2.2" = {
      name = "exenv";
      packageName = "exenv";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exenv/-/exenv-1.2.2.tgz";
        sha1 = "2ae78e85d9894158670b03d47bec1f03bd91bb9d";
      };
    };
    "history-3.3.0" = {
      name = "history";
      packageName = "history";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/history/-/history-3.3.0.tgz";
        sha1 = "fcedcce8f12975371545d735461033579a6dae9c";
      };
    };
    "warning-3.0.0" = {
      name = "warning";
      packageName = "warning";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/warning/-/warning-3.0.0.tgz";
        sha1 = "32e5377cb572de4ab04753bdf8821c01ed605b7c";
      };
    };
    "query-string-4.3.4" = {
      name = "query-string";
      packageName = "query-string";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/query-string/-/query-string-4.3.4.tgz";
        sha1 = "bbb693b9ca915c232515b228b1a02b609043dbeb";
      };
    };
    "strict-uri-encode-1.1.0" = {
      name = "strict-uri-encode";
      packageName = "strict-uri-encode";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strict-uri-encode/-/strict-uri-encode-1.1.0.tgz";
        sha1 = "279b225df1d582b1f54e65addd4352e18faa0713";
      };
    };
    "core-js-2.4.1" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz";
        sha1 = "4de911e667b0eae9124e34254b53aea6fc618d3e";
      };
    };
    "d3-interpolate-1.1.6" = {
      name = "d3-interpolate";
      packageName = "d3-interpolate";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-interpolate/-/d3-interpolate-1.1.6.tgz";
        sha512 = "3s4r4fjjgam0hcyi5drmnp2g9jqwdkbcvi58zhlcrp6vq8hag4k5va07s837krm76vv3rabdym4n3zvi1ggsw3v406kjrx9mzjyzscq";
      };
    };
    "d3-scale-1.0.4" = {
      name = "d3-scale";
      packageName = "d3-scale";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-scale/-/d3-scale-1.0.4.tgz";
        sha1 = "50e28bf6a193b706745528515ed9b3d44205a033";
      };
    };
    "d3-shape-1.0.4" = {
      name = "d3-shape";
      packageName = "d3-shape";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-shape/-/d3-shape-1.0.4.tgz";
        sha1 = "145ee100ccbec42f8e3f1996cd05c786f79fe1c6";
      };
    };
    "prop-types-15.5.10" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.5.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.5.10.tgz";
        sha1 = "2797dfc3126182e3a95e3dfbb2e893ddd7456154";
      };
    };
    "react-resize-detector-0.4.1" = {
      name = "react-resize-detector";
      packageName = "react-resize-detector";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-resize-detector/-/react-resize-detector-0.4.1.tgz";
        sha1 = "19f8b993e1e869e2879344e20dc23c4fac28b256";
      };
    };
    "react-smooth-0.3.0" = {
      name = "react-smooth";
      packageName = "react-smooth";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-smooth/-/react-smooth-0.3.0.tgz";
        sha1 = "b67665d7b9820257e34279c15e02e8e5131ebe99";
      };
    };
    "recharts-scale-0.3.2" = {
      name = "recharts-scale";
      packageName = "recharts-scale";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/recharts-scale/-/recharts-scale-0.3.2.tgz";
        sha1 = "dac7621714a4765d152cb2adbc30c73b831208c9";
      };
    };
    "reduce-css-calc-1.3.0" = {
      name = "reduce-css-calc";
      packageName = "reduce-css-calc";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/reduce-css-calc/-/reduce-css-calc-1.3.0.tgz";
        sha1 = "747c914e049614a4c9cfbba629871ad1d2927716";
      };
    };
    "d3-color-1.0.3" = {
      name = "d3-color";
      packageName = "d3-color";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-color/-/d3-color-1.0.3.tgz";
        sha1 = "bc7643fca8e53a8347e2fbdaffa236796b58509b";
      };
    };
    "d3-array-1.2.1" = {
      name = "d3-array";
      packageName = "d3-array";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-array/-/d3-array-1.2.1.tgz";
        sha512 = "03wg3x84q95i2fn5qvby7qdmrkcjs03rjhhc3ifqv7y8jd940kz90f98w17mir23fnmniy2dgkkkk8h15z0qi9pikl42f8j1ljhs8hb";
      };
    };
    "d3-collection-1.0.4" = {
      name = "d3-collection";
      packageName = "d3-collection";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-collection/-/d3-collection-1.0.4.tgz";
        sha1 = "342dfd12837c90974f33f1cc0a785aea570dcdc2";
      };
    };
    "d3-format-1.2.1" = {
      name = "d3-format";
      packageName = "d3-format";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-format/-/d3-format-1.2.1.tgz";
        sha512 = "3bpvnhl8x2bi8q0vz42axh2016g5sj0lplsynrgscfjm0qckgacz7x55nl290029ivmg7graixkpbspgzigha5ak9dssnypn1ad332k";
      };
    };
    "d3-time-1.0.8" = {
      name = "d3-time";
      packageName = "d3-time";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time/-/d3-time-1.0.8.tgz";
        sha512 = "0sxfl03cm5lmvypmsf74cnrd7a4jkq2i9pxcm3lga3arfvzglgdkkdzygi0yal6cw3jj6l5jg889knxqpdqlpvhfb51srk138v685k1";
      };
    };
    "d3-time-format-2.1.1" = {
      name = "d3-time-format";
      packageName = "d3-time-format";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-time-format/-/d3-time-format-2.1.1.tgz";
        sha512 = "2pp5w9c30lx87i4q7r7qxzq70z27g4wgasdaflihdckq1alrq1w18rlgjja77yimn8p2rg05pzls2rl2krb7gmpbgrwfn5ndb528h7j";
      };
    };
    "d3-path-1.0.5" = {
      name = "d3-path";
      packageName = "d3-path";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/d3-path/-/d3-path-1.0.5.tgz";
        sha1 = "241eb1849bd9e9e8021c0d0a799f8a0e8e441764";
      };
    };
    "raf-3.4.0" = {
      name = "raf";
      packageName = "raf";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/raf/-/raf-3.4.0.tgz";
        sha512 = "0dy6m7x3nq45cahsigaz5wm6s4ijpxqgq3lq9azjl1b4yngddk2wflhacfkr0f7lj0dfls1mhnhm460hksck7qhmvgq8pj0qhsgycx4";
      };
    };
    "react-transition-group-1.2.1" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-1.2.1.tgz";
        sha512 = "3fy687hpg5sh9plxi5hqf0dfhm9mm1wl6vs55li40g07z5i9hsh2m13hmzxn1yffjhwzqc524fk9rxkd4c6wjhpfw2h16l2avg8nrh9";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "chain-function-1.0.0" = {
      name = "chain-function";
      packageName = "chain-function";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chain-function/-/chain-function-1.0.0.tgz";
        sha1 = "0d4ab37e7e18ead0bdc47b920764118ce58733dc";
      };
    };
    "dom-helpers-3.3.1" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-3.3.1.tgz";
        sha512 = "2zcz2kln8jkdfzzpx3cinwvdp8gcvq2pm84i4d00w9z02pchp059hzmp96slidgidc6x1xz5aifp39s97y1xc6d9ji87vr7lqjvwafr";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "math-expression-evaluator-1.2.17" = {
      name = "math-expression-evaluator";
      packageName = "math-expression-evaluator";
      version = "1.2.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-expression-evaluator/-/math-expression-evaluator-1.2.17.tgz";
        sha1 = "de819fdbcd84dccd8fae59c6aeb79615b9d266ac";
      };
    };
    "reduce-function-call-1.0.2" = {
      name = "reduce-function-call";
      packageName = "reduce-function-call";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/reduce-function-call/-/reduce-function-call-1.0.2.tgz";
        sha1 = "5a200bf92e0e37751752fe45b0ab330fd4b6be99";
      };
    };
    "jssha-1.6.0" = {
      name = "jssha";
      packageName = "jssha";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jssha/-/jssha-1.6.0.tgz";
        sha1 = "67acf0b90fdebb9bb3fe3a44e6016cf2cf0670b9";
      };
    };
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "glossy-0.1.7" = {
      name = "glossy";
      packageName = "glossy";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glossy/-/glossy-0.1.7.tgz";
        sha1 = "769b5984a96f6066ab9ea758224825ee6c210f0b";
      };
    };
    "ultron-1.1.1" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.1.1.tgz";
        sha512 = "0x78hsv3jykmjl6qdqlqiz7v5nf06li8b5yvzpj6grnzwbcjch8ngyg55lm8g8mg4znvk7qbryvrr2dxacz3cvyb1nsm64qsw21g0ah";
      };
    };
  };
  args = rec {
    name = "daedalus";
    packageName = "daedalus";
    version = "0.8.0";
    #src = ./.;
    src = let
      source = srcOnly {
        name = "daedalus-source";
        src = fetchgit {
          url = "https://github.com/input-output-hk/daedalus";
          rev = version;
          sha256 = "01jxdzprhyr15nb6qhz25210jngqybisp2d0nivsdc77b4qikx88";
        };
        patches = [ ./package.patch ];
      };
    in source;


    # src = pkgs.fetchFromGitHub {
    #   owner = "input-output-hk";
    #   repo = pname;
    #   rev = version;
    #   sha256 = "65jxdzprhyr15nb6qhz25210jngqybisp2d0nivsdc77b4qikx88";
    # };
    dependencies = [
      sources."aes-js-2.1.1"
      sources."bignumber.js-4.0.0"
      (sources."bip39-2.3.0" // {
        dependencies = [
          (sources."create-hash-1.1.3" // {
            dependencies = [
              (sources."cipher-base-1.0.4" // {
                dependencies = [
                  sources."safe-buffer-5.1.1"
                ];
              })
              sources."inherits-2.0.3"
              (sources."ripemd160-2.0.1" // {
                dependencies = [
                  sources."hash-base-2.0.2"
                ];
              })
              (sources."sha.js-2.4.9" // {
                dependencies = [
                  sources."safe-buffer-5.1.1"
                ];
              })
            ];
          })
          (sources."pbkdf2-3.0.14" // {
            dependencies = [
              (sources."create-hmac-1.1.6" // {
                dependencies = [
                  sources."cipher-base-1.0.4"
                  sources."inherits-2.0.3"
                ];
              })
              (sources."ripemd160-2.0.1" // {
                dependencies = [
                  sources."hash-base-2.0.2"
                  sources."inherits-2.0.3"
                ];
              })
              sources."safe-buffer-5.1.1"
              (sources."sha.js-2.4.9" // {
                dependencies = [
                  sources."inherits-2.0.3"
                ];
              })
            ];
          })
          (sources."randombytes-2.0.5" // {
            dependencies = [
              sources."safe-buffer-5.1.1"
            ];
          })
          sources."unorm-1.4.1"
        ];
      })
      sources."blakejs-1.0.1"
      sources."classnames-2.2.5"
      (sources."css-modules-require-hook-4.0.6" // {
        dependencies = [
          (sources."debug-2.6.9" // {
            dependencies = [
              sources."ms-2.0.0"
            ];
          })
          (sources."generic-names-1.0.3" // {
            dependencies = [
              (sources."loader-utils-0.2.17" // {
                dependencies = [
                  sources."big.js-3.2.0"
                  sources."emojis-list-2.1.0"
                  sources."json5-0.5.1"
                  sources."object-assign-4.1.1"
                ];
              })
            ];
          })
          sources."glob-to-regexp-0.1.0"
          sources."icss-replace-symbols-1.1.0"
          (sources."postcss-modules-extract-imports-1.2.0" // {
            dependencies = [
              (sources."postcss-6.0.14" // {
                dependencies = [
                  (sources."chalk-2.3.0" // {
                    dependencies = [
                      (sources."ansi-styles-3.2.0" // {
                        dependencies = [
                          (sources."color-convert-1.9.1" // {
                            dependencies = [
                              sources."color-name-1.1.3"
                            ];
                          })
                        ];
                      })
                      sources."escape-string-regexp-1.0.5"
                    ];
                  })
                  sources."source-map-0.6.1"
                  (sources."supports-color-4.5.0" // {
                    dependencies = [
                      sources."has-flag-2.0.0"
                    ];
                  })
                ];
              })
            ];
          })
          (sources."postcss-modules-local-by-default-1.2.0" // {
            dependencies = [
              (sources."css-selector-tokenizer-0.7.0" // {
                dependencies = [
                  sources."cssesc-0.1.0"
                  sources."fastparse-1.1.1"
                  (sources."regexpu-core-1.0.0" // {
                    dependencies = [
                      sources."regenerate-1.3.3"
                      sources."regjsgen-0.2.0"
                      (sources."regjsparser-0.1.5" // {
                        dependencies = [
                          sources."jsesc-0.5.0"
                        ];
                      })
                    ];
                  })
                ];
              })
              (sources."postcss-6.0.14" // {
                dependencies = [
                  (sources."chalk-2.3.0" // {
                    dependencies = [
                      (sources."ansi-styles-3.2.0" // {
                        dependencies = [
                          (sources."color-convert-1.9.1" // {
                            dependencies = [
                              sources."color-name-1.1.3"
                            ];
                          })
                        ];
                      })
                      sources."escape-string-regexp-1.0.5"
                    ];
                  })
                  sources."source-map-0.6.1"
                  (sources."supports-color-4.5.0" // {
                    dependencies = [
                      sources."has-flag-2.0.0"
                    ];
                  })
                ];
              })
            ];
          })
          (sources."postcss-modules-parser-1.1.1" // {
            dependencies = [
              (sources."lodash.foreach-3.0.3" // {
                dependencies = [
                  sources."lodash._arrayeach-3.0.0"
                  (sources."lodash._baseeach-3.0.4" // {
                    dependencies = [
                      (sources."lodash.keys-3.1.2" // {
                        dependencies = [
                          sources."lodash._getnative-3.9.1"
                          sources."lodash.isarguments-3.1.0"
                        ];
                      })
                    ];
                  })
                  sources."lodash._bindcallback-3.0.1"
                  sources."lodash.isarray-3.0.4"
                ];
              })
            ];
          })
          (sources."postcss-modules-scope-1.1.0" // {
            dependencies = [
              (sources."css-selector-tokenizer-0.7.0" // {
                dependencies = [
                  sources."cssesc-0.1.0"
                  sources."fastparse-1.1.1"
                  (sources."regexpu-core-1.0.0" // {
                    dependencies = [
                      sources."regenerate-1.3.3"
                      sources."regjsgen-0.2.0"
                      (sources."regjsparser-0.1.5" // {
                        dependencies = [
                          sources."jsesc-0.5.0"
                        ];
                      })
                    ];
                  })
                ];
              })
              (sources."postcss-6.0.14" // {
                dependencies = [
                  (sources."chalk-2.3.0" // {
                    dependencies = [
                      (sources."ansi-styles-3.2.0" // {
                        dependencies = [
                          (sources."color-convert-1.9.1" // {
                            dependencies = [
                              sources."color-name-1.1.3"
                            ];
                          })
                        ];
                      })
                      sources."escape-string-regexp-1.0.5"
                    ];
                  })
                  sources."source-map-0.6.1"
                  (sources."supports-color-4.5.0" // {
                    dependencies = [
                      sources."has-flag-2.0.0"
                    ];
                  })
                ];
              })
            ];
          })
          (sources."postcss-modules-values-1.3.0" // {
            dependencies = [
              (sources."postcss-6.0.14" // {
                dependencies = [
                  (sources."chalk-2.3.0" // {
                    dependencies = [
                      (sources."ansi-styles-3.2.0" // {
                        dependencies = [
                          (sources."color-convert-1.9.1" // {
                            dependencies = [
                              sources."color-name-1.1.3"
                            ];
                          })
                        ];
                      })
                      sources."escape-string-regexp-1.0.5"
                    ];
                  })
                  sources."source-map-0.6.1"
                  (sources."supports-color-4.5.0" // {
                    dependencies = [
                      sources."has-flag-2.0.0"
                    ];
                  })
                ];
              })
            ];
          })
          sources."seekout-1.0.2"
        ];
      })
      (sources."electron-debug-1.1.0" // {
        dependencies = [
          sources."electron-is-dev-0.1.2"
          sources."electron-localshortcut-0.6.1"
        ];
      })
      (sources."electron-json-storage-3.0.4" // {
        dependencies = [
          sources."async-2.6.0"
          (sources."mkdirp-0.5.1" // {
            dependencies = [
              sources."minimist-0.0.8"
            ];
          })
          (sources."rimraf-2.6.2" // {
            dependencies = [
              (sources."glob-7.1.2" // {
                dependencies = [
                  sources."fs.realpath-1.0.0"
                  (sources."inflight-1.0.6" // {
                    dependencies = [
                      sources."wrappy-1.0.2"
                    ];
                  })
                  sources."inherits-2.0.3"
                  (sources."minimatch-3.0.4" // {
                    dependencies = [
                      (sources."brace-expansion-1.1.8" // {
                        dependencies = [
                          sources."balanced-match-1.0.0"
                          sources."concat-map-0.0.1"
                        ];
                      })
                    ];
                  })
                  (sources."once-1.4.0" // {
                    dependencies = [
                      sources."wrappy-1.0.2"
                    ];
                  })
                  sources."path-is-absolute-1.0.1"
                ];
              })
            ];
          })
        ];
      })
      sources."electron-log-2.0.2"
      sources."es6-error-4.0.2"
      sources."faker-3.1.0"
      (sources."html-loader-0.4.5" // {
        dependencies = [
          (sources."es6-templates-0.2.3" // {
            dependencies = [
              (sources."recast-0.11.23" // {
                dependencies = [
                  sources."ast-types-0.9.6"
                  sources."esprima-3.1.3"
                  sources."private-0.1.8"
                  sources."source-map-0.5.7"
                ];
              })
              sources."through-2.3.8"
            ];
          })
          sources."fastparse-1.1.1"
          (sources."html-minifier-3.5.8" // {
            dependencies = [
              (sources."camel-case-3.0.0" // {
                dependencies = [
                  (sources."no-case-2.3.2" // {
                    dependencies = [
                      sources."lower-case-1.1.4"
                    ];
                  })
                  sources."upper-case-1.1.3"
                ];
              })
              (sources."clean-css-4.1.9" // {
                dependencies = [
                  sources."source-map-0.5.7"
                ];
              })
              sources."commander-2.12.2"
              sources."he-1.1.1"
              (sources."ncname-1.0.0" // {
                dependencies = [
                  sources."xml-char-classes-1.0.0"
                ];
              })
              (sources."param-case-2.1.1" // {
                dependencies = [
                  (sources."no-case-2.3.2" // {
                    dependencies = [
                      sources."lower-case-1.1.4"
                    ];
                  })
                ];
              })
              sources."relateurl-0.2.7"
              (sources."uglify-js-3.3.3" // {
                dependencies = [
                  sources."source-map-0.6.1"
                ];
              })
            ];
          })
          (sources."loader-utils-1.1.0" // {
            dependencies = [
              sources."big.js-3.2.0"
              sources."emojis-list-2.1.0"
              sources."json5-0.5.1"
            ];
          })
          sources."object-assign-4.1.1"
        ];
      })
      (sources."immutability-helper-2.1.2" // {
        dependencies = [
          (sources."invariant-2.2.2" // {
            dependencies = [
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.2"
                ];
              })
            ];
          })
        ];
      })
      sources."lodash-4.17.4"
      (sources."markdown-loader-2.0.0" // {
        dependencies = [
          (sources."loader-utils-0.2.17" // {
            dependencies = [
              sources."big.js-3.2.0"
              sources."emojis-list-2.1.0"
              sources."json5-0.5.1"
              sources."object-assign-4.1.1"
            ];
          })
          sources."marked-0.3.9"
        ];
      })
      sources."mobx-3.1.7"
      (sources."mobx-react-4.1.5" // {
        dependencies = [
          sources."hoist-non-react-statics-1.2.0"
        ];
      })
      sources."mobx-react-form-1.31.5"
      sources."mobx-react-router-3.1.2"
      sources."moment-2.18.1"
      sources."numeral-2.0.6"
      (sources."pdf.js-extract-0.0.5" // {
        dependencies = [
          sources."pdfjs-dist-for-node-1.0.893"
        ];
      })
      (sources."postcss-5.2.16" // {
        dependencies = [
          (sources."chalk-1.1.3" // {
            dependencies = [
              sources."ansi-styles-2.2.1"
              sources."escape-string-regexp-1.0.5"
              (sources."has-ansi-2.0.0" // {
                dependencies = [
                  sources."ansi-regex-2.1.1"
                ];
              })
              (sources."strip-ansi-3.0.1" // {
                dependencies = [
                  sources."ansi-regex-2.1.1"
                ];
              })
              sources."supports-color-2.0.0"
            ];
          })
          sources."js-base64-2.4.0"
          sources."source-map-0.5.7"
          (sources."supports-color-3.2.3" // {
            dependencies = [
              sources."has-flag-1.0.0"
            ];
          })
        ];
      })
      (sources."qrcode.react-0.6.1" // {
        dependencies = [
          sources."qr.js-0.0.0"
        ];
      })
      sources."random-words-0.0.1"
      sources."raw-loader-0.5.1"
      (sources."react-15.4.2" // {
        dependencies = [
          (sources."fbjs-0.8.16" // {
            dependencies = [
              sources."core-js-1.2.7"
              (sources."isomorphic-fetch-2.2.1" // {
                dependencies = [
                  (sources."node-fetch-1.7.3" // {
                    dependencies = [
                      (sources."encoding-0.1.12" // {
                        dependencies = [
                          sources."iconv-lite-0.4.19"
                        ];
                      })
                      sources."is-stream-1.1.0"
                    ];
                  })
                  sources."whatwg-fetch-2.0.3"
                ];
              })
              (sources."promise-7.3.1" // {
                dependencies = [
                  sources."asap-2.0.6"
                ];
              })
              sources."setimmediate-1.0.5"
              sources."ua-parser-js-0.7.17"
            ];
          })
          (sources."loose-envify-1.3.1" // {
            dependencies = [
              sources."js-tokens-3.0.2"
            ];
          })
          sources."object-assign-4.1.1"
        ];
      })
      (sources."react-addons-css-transition-group-15.4.2" // {
        dependencies = [
          (sources."fbjs-0.8.16" // {
            dependencies = [
              sources."core-js-1.2.7"
              (sources."isomorphic-fetch-2.2.1" // {
                dependencies = [
                  (sources."node-fetch-1.7.3" // {
                    dependencies = [
                      (sources."encoding-0.1.12" // {
                        dependencies = [
                          sources."iconv-lite-0.4.19"
                        ];
                      })
                      sources."is-stream-1.1.0"
                    ];
                  })
                  sources."whatwg-fetch-2.0.3"
                ];
              })
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.2"
                ];
              })
              (sources."promise-7.3.1" // {
                dependencies = [
                  sources."asap-2.0.6"
                ];
              })
              sources."setimmediate-1.0.5"
              sources."ua-parser-js-0.7.17"
            ];
          })
          sources."object-assign-4.1.1"
        ];
      })
      (sources."react-copy-to-clipboard-4.2.3" // {
        dependencies = [
          (sources."copy-to-clipboard-3.0.8" // {
            dependencies = [
              sources."toggle-selection-1.0.6"
            ];
          })
        ];
      })
      (sources."react-css-themr-2.0.0" // {
        dependencies = [
          (sources."invariant-2.2.2" // {
            dependencies = [
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.2"
                ];
              })
            ];
          })
        ];
      })
      (sources."react-dom-15.4.2" // {
        dependencies = [
          (sources."fbjs-0.8.16" // {
            dependencies = [
              sources."core-js-1.2.7"
              (sources."isomorphic-fetch-2.2.1" // {
                dependencies = [
                  (sources."node-fetch-1.7.3" // {
                    dependencies = [
                      (sources."encoding-0.1.12" // {
                        dependencies = [
                          sources."iconv-lite-0.4.19"
                        ];
                      })
                      sources."is-stream-1.1.0"
                    ];
                  })
                  sources."whatwg-fetch-2.0.3"
                ];
              })
              (sources."promise-7.3.1" // {
                dependencies = [
                  sources."asap-2.0.6"
                ];
              })
              sources."setimmediate-1.0.5"
              sources."ua-parser-js-0.7.17"
            ];
          })
          (sources."loose-envify-1.3.1" // {
            dependencies = [
              sources."js-tokens-3.0.2"
            ];
          })
          sources."object-assign-4.1.1"
        ];
      })
      (sources."react-dropzone-3.12.2" // {
        dependencies = [
          sources."attr-accept-1.1.0"
        ];
      })
      (sources."react-intl-2.2.3" // {
        dependencies = [
          sources."intl-format-cache-2.1.0"
          (sources."intl-messageformat-1.3.0" // {
            dependencies = [
              sources."intl-messageformat-parser-1.2.0"
            ];
          })
          sources."intl-relativeformat-1.3.0"
          (sources."invariant-2.2.2" // {
            dependencies = [
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.2"
                ];
              })
            ];
          })
        ];
      })
      (sources."react-markdown-2.5.0" // {
        dependencies = [
          (sources."commonmark-0.24.0" // {
            dependencies = [
              sources."entities-1.1.1"
              sources."mdurl-1.0.1"
              sources."string.prototype.repeat-0.2.0"
            ];
          })
          (sources."commonmark-react-renderer-4.3.4" // {
            dependencies = [
              sources."lodash.assign-4.2.0"
              sources."lodash.isplainobject-4.0.6"
              sources."pascalcase-0.1.1"
              sources."xss-filters-1.2.7"
            ];
          })
          sources."in-publish-2.0.0"
          (sources."prop-types-15.6.0" // {
            dependencies = [
              (sources."fbjs-0.8.16" // {
                dependencies = [
                  sources."core-js-1.2.7"
                  (sources."isomorphic-fetch-2.2.1" // {
                    dependencies = [
                      (sources."node-fetch-1.7.3" // {
                        dependencies = [
                          (sources."encoding-0.1.12" // {
                            dependencies = [
                              sources."iconv-lite-0.4.19"
                            ];
                          })
                          sources."is-stream-1.1.0"
                        ];
                      })
                      sources."whatwg-fetch-2.0.3"
                    ];
                  })
                  (sources."promise-7.3.1" // {
                    dependencies = [
                      sources."asap-2.0.6"
                    ];
                  })
                  sources."setimmediate-1.0.5"
                  sources."ua-parser-js-0.7.17"
                ];
              })
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.2"
                ];
              })
              sources."object-assign-4.1.1"
            ];
          })
        ];
      })
      sources."react-number-format-1.1.2"
      (sources."react-polymorph-0.3.1" // {
        dependencies = [
          sources."postinstall-build-5.0.1"
          (sources."react-modal-2.4.1" // {
            dependencies = [
              sources."exenv-1.2.2"
              (sources."prop-types-15.6.0" // {
                dependencies = [
                  (sources."fbjs-0.8.16" // {
                    dependencies = [
                      sources."core-js-1.2.7"
                      (sources."isomorphic-fetch-2.2.1" // {
                        dependencies = [
                          (sources."node-fetch-1.7.3" // {
                            dependencies = [
                              (sources."encoding-0.1.12" // {
                                dependencies = [
                                  sources."iconv-lite-0.4.19"
                                ];
                              })
                              sources."is-stream-1.1.0"
                            ];
                          })
                          sources."whatwg-fetch-2.0.3"
                        ];
                      })
                      (sources."promise-7.3.1" // {
                        dependencies = [
                          sources."asap-2.0.6"
                        ];
                      })
                      sources."setimmediate-1.0.5"
                      sources."ua-parser-js-0.7.17"
                    ];
                  })
                  (sources."loose-envify-1.3.1" // {
                    dependencies = [
                      sources."js-tokens-3.0.2"
                    ];
                  })
                  sources."object-assign-4.1.1"
                ];
              })
            ];
          })
        ];
      })
      (sources."react-router-3.0.3" // {
        dependencies = [
          (sources."history-3.3.0" // {
            dependencies = [
              (sources."query-string-4.3.4" // {
                dependencies = [
                  sources."object-assign-4.1.1"
                  sources."strict-uri-encode-1.1.0"
                ];
              })
            ];
          })
          sources."hoist-non-react-statics-1.2.0"
          sources."invariant-2.2.2"
          (sources."loose-envify-1.3.1" // {
            dependencies = [
              sources."js-tokens-3.0.2"
            ];
          })
          sources."warning-3.0.0"
        ];
      })
      (sources."react-svg-inline-2.0.0" // {
        dependencies = [
          (sources."prop-types-15.6.0" // {
            dependencies = [
              (sources."fbjs-0.8.16" // {
                dependencies = [
                  sources."core-js-1.2.7"
                  (sources."isomorphic-fetch-2.2.1" // {
                    dependencies = [
                      (sources."node-fetch-1.7.3" // {
                        dependencies = [
                          (sources."encoding-0.1.12" // {
                            dependencies = [
                              sources."iconv-lite-0.4.19"
                            ];
                          })
                          sources."is-stream-1.1.0"
                        ];
                      })
                      sources."whatwg-fetch-2.0.3"
                    ];
                  })
                  (sources."promise-7.3.1" // {
                    dependencies = [
                      sources."asap-2.0.6"
                    ];
                  })
                  sources."setimmediate-1.0.5"
                  sources."ua-parser-js-0.7.17"
                ];
              })
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.2"
                ];
              })
              sources."object-assign-4.1.1"
            ];
          })
        ];
      })
      (sources."recharts-1.0.0-alpha.4" // {
        dependencies = [
          sources."core-js-2.4.1"
          (sources."d3-interpolate-1.1.6" // {
            dependencies = [
              sources."d3-color-1.0.3"
            ];
          })
          (sources."d3-scale-1.0.4" // {
            dependencies = [
              sources."d3-array-1.2.1"
              sources."d3-collection-1.0.4"
              sources."d3-color-1.0.3"
              sources."d3-format-1.2.1"
              sources."d3-time-1.0.8"
              sources."d3-time-format-2.1.1"
            ];
          })
          (sources."d3-shape-1.0.4" // {
            dependencies = [
              sources."d3-path-1.0.5"
            ];
          })
          (sources."prop-types-15.5.10" // {
            dependencies = [
              (sources."fbjs-0.8.16" // {
                dependencies = [
                  sources."core-js-1.2.7"
                  (sources."isomorphic-fetch-2.2.1" // {
                    dependencies = [
                      (sources."node-fetch-1.7.3" // {
                        dependencies = [
                          (sources."encoding-0.1.12" // {
                            dependencies = [
                              sources."iconv-lite-0.4.19"
                            ];
                          })
                          sources."is-stream-1.1.0"
                        ];
                      })
                      sources."whatwg-fetch-2.0.3"
                    ];
                  })
                  sources."object-assign-4.1.1"
                  (sources."promise-7.3.1" // {
                    dependencies = [
                      sources."asap-2.0.6"
                    ];
                  })
                  sources."setimmediate-1.0.5"
                  sources."ua-parser-js-0.7.17"
                ];
              })
              (sources."loose-envify-1.3.1" // {
                dependencies = [
                  sources."js-tokens-3.0.2"
                ];
              })
            ];
          })
          sources."react-resize-detector-0.4.1"
          (sources."react-smooth-0.3.0" // {
            dependencies = [
              (sources."raf-3.4.0" // {
                dependencies = [
                  sources."performance-now-2.1.0"
                ];
              })
              (sources."react-transition-group-1.2.1" // {
                dependencies = [
                  sources."chain-function-1.0.0"
                  sources."dom-helpers-3.3.1"
                  (sources."loose-envify-1.3.1" // {
                    dependencies = [
                      sources."js-tokens-3.0.2"
                    ];
                  })
                  sources."warning-3.0.0"
                ];
              })
            ];
          })
          sources."recharts-scale-0.3.2"
          (sources."reduce-css-calc-1.3.0" // {
            dependencies = [
              sources."balanced-match-0.4.2"
              sources."math-expression-evaluator-1.2.17"
              sources."reduce-function-call-1.0.2"
            ];
          })
        ];
      })
      sources."route-parser-0.0.5"
      (sources."source-map-support-0.4.14" // {
        dependencies = [
          sources."source-map-0.5.7"
        ];
      })
      sources."validator-6.3.0"
      (sources."wallet-address-validator-0.1.0" // {
        dependencies = [
          sources."jssha-1.6.0"
        ];
      })
      (sources."winston-2.3.1" // {
        dependencies = [
          sources."async-1.0.0"
          sources."colors-1.0.3"
          sources."cycle-1.0.3"
          sources."eyes-0.1.8"
          sources."isstream-0.1.2"
          sources."stack-trace-0.0.10"
        ];
      })
      (sources."winston-papertrail-1.0.4" // {
        dependencies = [
          sources."glossy-0.1.7"
        ];
      })
      (sources."ws-3.1.0" // {
        dependencies = [
          sources."safe-buffer-5.1.1"
          sources."ultron-1.1.1"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Cryptocurrency Wallet";
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
