# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  postinstall-build = nodeEnv.buildNodePackage {
    name = "postinstall-build";
    packageName = "postinstall-build";
    version = "5.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/postinstall-build/-/postinstall-build-5.0.1.tgz";
      sha1 = "b917a9079b26178d9a24af5a5cd8cb4a991d11b9";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Helper for conditionally building your npm package on postinstall in order to support git installs.";
      homepage = "https://github.com/exogen/postinstall-build#readme";
      license = "MIT";
    };
    production = true;
  };
}